# Generated by Django 5.0.2 on 2025-11-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamEloHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.IntegerField(db_index=True, help_text="球隊 ID")),
                ("date", models.DateField(db_index=True, help_text="評分日期")),
                ("season", models.IntegerField(db_index=True, help_text="賽季年份")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Elo 評分 (通常在 1200-1800 之間)",
                        max_digits=8,
                    ),
                ),
                (
                    "is_season_start",
                    models.BooleanField(default=False, help_text="是否為季初回歸後的初始分數"),
                ),
            ],
            options={
                "verbose_name": "Team Elo History",
                "verbose_name_plural": "Team Elo Histories",
                "db_table": "team_elo_history",
                "ordering": ["date", "team_id"],
                "indexes": [
                    models.Index(
                        fields=["team_id", "season"],
                        name="team_elo_hi_team_id_a494f1_idx",
                    ),
                    models.Index(
                        fields=["season", "date"], name="team_elo_hi_season_a34957_idx"
                    ),
                ],
                "unique_together": {("team_id", "date")},
            },
        ),
    ]
